set_property PACKAGE_PIN W5 [get_ports clk100M]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M]

set_property PACKAGE_PIN R18 [get_ports i2c_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sclk]
set_property PACKAGE_PIN P18 [get_ports i2c_sdat]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sdat]
set_property PACKAGE_PIN N17 [get_ports camera_href]
set_property IOSTANDARD LVCMOS33 [get_ports camera_href]
set_property PACKAGE_PIN P17 [get_ports camera_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vsync]
set_property PACKAGE_PIN M19 [get_ports camera_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_pclk]
set_property PACKAGE_PIN A14 [get_ports camera_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports camera_pwdn]
set_property PACKAGE_PIN M18 [get_ports camera_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_xclk]
set_property PACKAGE_PIN A15 [get_ports camera_rst]
set_property IOSTANDARD LVCMOS33 [get_ports camera_rst]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets camera_pclk_IBUF]

set_property PACKAGE_PIN L17 [get_ports camera_data[7]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[7]]
set_property PACKAGE_PIN K17 [get_ports camera_data[6]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[6]]
set_property PACKAGE_PIN C16 [get_ports camera_data[5]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[5]]
set_property PACKAGE_PIN B16 [get_ports camera_data[4]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[4]]
set_property PACKAGE_PIN C15 [get_ports camera_data[3]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[3]]
set_property PACKAGE_PIN B15 [get_ports camera_data[2]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[2]]
set_property PACKAGE_PIN A17 [get_ports camera_data[1]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[1]]
set_property PACKAGE_PIN A16 [get_ports camera_data[0]]
set_property IOSTANDARD LVCMOS33 [get_ports camera_data[0]]

set_property PACKAGE_PIN N19 [get_ports vga_r[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[3]]
set_property PACKAGE_PIN J19 [get_ports vga_r[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[2]]
set_property PACKAGE_PIN H19 [get_ports vga_r[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[1]]
set_property PACKAGE_PIN G19 [get_ports vga_r[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_r[0]]

set_property PACKAGE_PIN D17 [get_ports vga_g[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[3]]
set_property PACKAGE_PIN G17 [get_ports vga_g[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[2]]
set_property PACKAGE_PIN H17 [get_ports vga_g[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[1]]
set_property PACKAGE_PIN J17 [get_ports vga_g[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_g[0]]

set_property PACKAGE_PIN J18 [get_ports vga_b[3]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[3]]
set_property PACKAGE_PIN K18 [get_ports vga_b[2]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[2]]
set_property PACKAGE_PIN L18 [get_ports vga_b[1]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[1]]
set_property PACKAGE_PIN N18 [get_ports vga_b[0]]
set_property IOSTANDARD LVCMOS33 [get_ports vga_b[0]]

set_property PACKAGE_PIN P19 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property PACKAGE_PIN R19 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]

set_property PACKAGE_PIN U18 [get_ports key1]
set_property IOSTANDARD LVCMOS33 [get_ports key1]
set_property PACKAGE_PIN R2 [get_ports key_mode]
set_property IOSTANDARD LVCMOS33 [get_ports key_mode]
set_property PACKAGE_PIN T1 [get_ports key2]
set_property IOSTANDARD LVCMOS33 [get_ports key2]

set_property PACKAGE_PIN V16 [get_ports Judge_mode[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Judge_mode[1]]
set_property PACKAGE_PIN V17 [get_ports Judge_mode[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Judge_mode[0]]

set_property PACKAGE_PIN L1 [get_ports led[15]]
set_property IOSTANDARD LVCMOS33 [get_ports led[15]]
set_property PACKAGE_PIN P1 [get_ports led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property PACKAGE_PIN N3 [get_ports led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property PACKAGE_PIN P3 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property PACKAGE_PIN U3 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property PACKAGE_PIN W3 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property PACKAGE_PIN V3 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property PACKAGE_PIN V13 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]

set_property PACKAGE_PIN V14 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property PACKAGE_PIN U14 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property PACKAGE_PIN U15 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property PACKAGE_PIN W18 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property PACKAGE_PIN V19 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property PACKAGE_PIN U19 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN E19 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN U16 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]

set_property PACKAGE_PIN W16 [get_ports key_lock]
set_property IOSTANDARD LVCMOS33 [get_ports key_lock]

set_property PACKAGE_PIN J1 [get_ports PWM_X]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_X]
set_property PACKAGE_PIN L2 [get_ports PWM_Y]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_Y]