#recorrect in 3.19
#write_cfgmem -format mcs -interface spix4 -size 128 -loadbit "up 0x0 C:/Users/lenovo/Desktop/pin_assign/pin_assign.runs/impl_1/pin_assign.bit" -file FPGA_TOP.mcs -force
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
#set_property DCI_CASCADE {32 34} [get_iobanks 33]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]
#set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-2 [current_design]


set_property PACKAGE_PIN J14 [get_ports {EIM_D[15]}]
set_property PACKAGE_PIN C14 [get_ports {EIM_D[14]}]
set_property PACKAGE_PIN G13 [get_ports {EIM_D[13]}]
set_property PACKAGE_PIN K14 [get_ports {EIM_D[12]}]
set_property PACKAGE_PIN H15 [get_ports {EIM_D[11]}]
set_property PACKAGE_PIN F15 [get_ports {EIM_D[10]}]
set_property PACKAGE_PIN B15 [get_ports {EIM_D[9]}]
set_property PACKAGE_PIN G15 [get_ports {EIM_D[8]}]
set_property PACKAGE_PIN L16 [get_ports {EIM_D[7]}]
set_property PACKAGE_PIN K15 [get_ports {EIM_D[6]}]
set_property PACKAGE_PIN G14 [get_ports {EIM_D[5]}]
set_property PACKAGE_PIN E15 [get_ports {EIM_D[4]}]
set_property PACKAGE_PIN C15 [get_ports {EIM_D[3]}]
set_property PACKAGE_PIN J16 [get_ports {EIM_D[2]}]
set_property PACKAGE_PIN H16 [get_ports {EIM_D[1]}]
set_property PACKAGE_PIN K16 [get_ports {EIM_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_D[0]}]

set_property PACKAGE_PIN J11 [get_ports {EIM_DA[15]}]
set_property PACKAGE_PIN J12 [get_ports {EIM_DA[14]}]
set_property PACKAGE_PIN B13 [get_ports {EIM_DA[13]}]
set_property PACKAGE_PIN F13 [get_ports {EIM_DA[12]}]
set_property PACKAGE_PIN F11 [get_ports {EIM_DA[11]}]
set_property PACKAGE_PIN D12 [get_ports {EIM_DA[10]}]
set_property PACKAGE_PIN G12 [get_ports {EIM_DA[9]}]
set_property PACKAGE_PIN E13 [get_ports {EIM_DA[8]}]
set_property PACKAGE_PIN L15 [get_ports {EIM_DA[7]}]
set_property PACKAGE_PIN A15 [get_ports {EIM_DA[6]}]
set_property PACKAGE_PIN D13 [get_ports {EIM_DA[5]}]
set_property PACKAGE_PIN L12 [get_ports {EIM_DA[4]}]
set_property PACKAGE_PIN K13 [get_ports {EIM_DA[3]}]
set_property PACKAGE_PIN F12 [get_ports {EIM_DA[2]}]
set_property PACKAGE_PIN D14 [get_ports {EIM_DA[1]}]
set_property PACKAGE_PIN C12 [get_ports {EIM_DA[0]}]
set_property PACKAGE_PIN E14 [get_ports {EIM_OE}]
set_property PACKAGE_PIN H14 [get_ports {EIM_CS0}]
set_property PACKAGE_PIN A13 [get_ports {EIM_WAIT}]
set_property PACKAGE_PIN J13 [get_ports {EIM_LBA}]
set_property PACKAGE_PIN B14 [get_ports {EIM_RW}]
set_property PACKAGE_PIN H12 [get_ports {EIM_BCLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_DA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_OE}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_CS0}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_WAIT}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_LBA}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_RW}]
set_property IOSTANDARD LVCMOS33 [get_ports {EIM_BCLK}]

set_property PACKAGE_PIN E16 [get_ports {BUTTON[1]}]
set_property PACKAGE_PIN F16 [get_ports {BUTTON[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUTTON[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BUTTON[0]}]

set_property PACKAGE_PIN D11 [get_ports {LAMPEN_IMX}]
set_property PACKAGE_PIN C11 [get_ports {LAMPEN_FPGA}]
set_property IOSTANDARD LVCMOS33 [get_ports {LAMPEN_IMX}]
set_property IOSTANDARD LVCMOS33 [get_ports {LAMPEN_FPGA}]

set_property PACKAGE_PIN A12 [get_ports {CW_INDEX}]
set_property IOSTANDARD LVCMOS33 [get_ports {CW_INDEX}]

set_property PACKAGE_PIN A11 [get_ports {IMX_I2C_SCL}]
set_property PACKAGE_PIN E11 [get_ports {IMX_I2C_SDA}]
set_property IOSTANDARD LVCMOS33 [get_ports {IMX_I2C_SCL}]
set_property IOSTANDARD LVCMOS33 [get_ports {IMX_I2C_SDA}]

set_property PACKAGE_PIN G19 [get_ports {LED[3]}]
set_property PACKAGE_PIN E20 [get_ports {LED[2]}]
set_property PACKAGE_PIN D18 [get_ports {LED[1]}]
set_property PACKAGE_PIN E18 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LED[0]}]

set_property PACKAGE_PIN D16 [get_ports {SWITCH[3]}]
set_property PACKAGE_PIN C16 [get_ports {SWITCH[2]}]
set_property PACKAGE_PIN A16 [get_ports {SWITCH[1]}]
set_property PACKAGE_PIN A17 [get_ports {SWITCH[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SWITCH[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SWITCH[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SWITCH[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {SWITCH[0]}]

set_property PACKAGE_PIN AC25 [get_ports {PVI[35]}]
set_property PACKAGE_PIN AC24 [get_ports {PVI[34]}]
set_property PACKAGE_PIN AD23 [get_ports {PVI[33]}]
set_property PACKAGE_PIN AD24 [get_ports {PVI[32]}]
set_property PACKAGE_PIN AE25 [get_ports {PVI[31]}]
set_property PACKAGE_PIN AE24 [get_ports {PVI[30]}]
set_property PACKAGE_PIN AF25 [get_ports {PVI[29]}]
set_property PACKAGE_PIN AF23 [get_ports {PVI[28]}]
set_property PACKAGE_PIN AG24 [get_ports {PVI[27]}]
set_property PACKAGE_PIN AG22 [get_ports {PVI[26]}]
set_property PACKAGE_PIN AH25 [get_ports {PVI[25]}]
set_property PACKAGE_PIN AG25 [get_ports {PVI[24]}]
set_property PACKAGE_PIN AK25 [get_ports {PVI[23]}]
set_property PACKAGE_PIN AJ24 [get_ports {PVI[22]}]
set_property PACKAGE_PIN AH24 [get_ports {PVI[21]}]
set_property PACKAGE_PIN AK24 [get_ports {PVI[20]}]
set_property PACKAGE_PIN AJ23 [get_ports {PVI[19]}]
set_property PACKAGE_PIN AG23 [get_ports {PVI[18]}]
set_property PACKAGE_PIN AH21 [get_ports {PVI[17]}]
set_property PACKAGE_PIN AK21 [get_ports {PVI[16]}]
set_property PACKAGE_PIN AH20 [get_ports {PVI[15]}]
set_property PACKAGE_PIN AE20 [get_ports {PVI[14]}]
set_property PACKAGE_PIN AK20 [get_ports {PVI[13]}]
set_property PACKAGE_PIN AD21 [get_ports {PVI[12]}]
set_property PACKAGE_PIN AC20 [get_ports {PVI[11]}]
set_property PACKAGE_PIN AC21 [get_ports {PVI[10]}]
set_property PACKAGE_PIN AC22 [get_ports {PVI[9]}]
set_property PACKAGE_PIN AB20 [get_ports {PVI[8]}]
set_property PACKAGE_PIN AB22 [get_ports {PVI[7]}]
set_property PACKAGE_PIN AB23 [get_ports {PVI[6]}]
set_property PACKAGE_PIN AA20 [get_ports {PVI[5]}]
set_property PACKAGE_PIN AA21 [get_ports {PVI[4]}]
set_property PACKAGE_PIN AA22 [get_ports {PVI[3]}]
set_property PACKAGE_PIN Y20 [get_ports {PVI[2]}]
set_property PACKAGE_PIN Y23 [get_ports {PVI[1]}]
set_property PACKAGE_PIN Y21 [get_ports {PVI[0]}]
set_property PACKAGE_PIN AJ21 [get_ports {PVI_CLK}]
set_property PACKAGE_PIN AH22 [get_ports {PVI_DE}]
set_property PACKAGE_PIN AJ22 [get_ports {PVI_HSYNC}]
set_property PACKAGE_PIN AK23 [get_ports {PVI_VSYNC}]

set_property IOSTANDARD LVCMOS33 [get_ports {PVI[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI_CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI_DE}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI_HSYNC}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVI_VSYNC}]

set_property PACKAGE_PIN AF26 [get_ports {PVO[35]}]
set_property PACKAGE_PIN AK26 [get_ports {PVO[34]}]
set_property PACKAGE_PIN AJ26 [get_ports {PVO[33]}]
set_property PACKAGE_PIN AF27 [get_ports {PVO[32]}]
set_property PACKAGE_PIN AG27 [get_ports {PVO[31]}]
set_property PACKAGE_PIN AE28 [get_ports {PVO[30]}]
set_property PACKAGE_PIN AG28 [get_ports {PVO[29]}]
set_property PACKAGE_PIN AD28 [get_ports {PVO[28]}]
set_property PACKAGE_PIN AE30 [get_ports {PVO[27]}]
set_property PACKAGE_PIN AH29 [get_ports {PVO[26]}]
set_property PACKAGE_PIN AE29 [get_ports {PVO[25]}]
set_property PACKAGE_PIN AH30 [get_ports {PVO[24]}]
set_property PACKAGE_PIN AG30 [get_ports {PVO[23]}]
set_property PACKAGE_PIN AC26 [get_ports {PVO[22]}]
set_property PACKAGE_PIN AC30 [get_ports {PVO[21]}]
set_property PACKAGE_PIN AC29 [get_ports {PVO[20]}]
set_property PACKAGE_PIN W28 [get_ports {PVO[19]}]
set_property PACKAGE_PIN W27 [get_ports {PVO[18]}]
set_property PACKAGE_PIN Y26 [get_ports {PVO[17]}]
set_property PACKAGE_PIN Y25 [get_ports {PVO[16]}]
set_property PACKAGE_PIN AA26 [get_ports {PVO[15]}]
set_property PACKAGE_PIN AA25 [get_ports {PVO[14]}]
set_property PACKAGE_PIN AB27 [get_ports {PVO[13]}]
set_property PACKAGE_PIN AB25 [get_ports {PVO[12]}]
set_property PACKAGE_PIN AD26 [get_ports {PVO[11]}]
set_property PACKAGE_PIN AD27 [get_ports {PVO[10]}]
set_property PACKAGE_PIN W29 [get_ports {PVO[9]}]
set_property PACKAGE_PIN Y28 [get_ports {PVO[8]}]
set_property PACKAGE_PIN Y30 [get_ports {PVO[7]}]
set_property PACKAGE_PIN Y29 [get_ports {PVO[6]}]
set_property PACKAGE_PIN AA28 [get_ports {PVO[5]}]
set_property PACKAGE_PIN AA30 [get_ports {PVO[4]}]
set_property PACKAGE_PIN AA27 [get_ports {PVO[3]}]
set_property PACKAGE_PIN AB28 [get_ports {PVO[2]}]
set_property PACKAGE_PIN AB30 [get_ports {PVO[1]}]
set_property PACKAGE_PIN AB29 [get_ports {PVO[0]}]
set_property PACKAGE_PIN AG29 [get_ports {PVO_CLK}]
set_property PACKAGE_PIN AK30 [get_ports {PVO_DE}]
set_property PACKAGE_PIN AF30 [get_ports {PVO_HSYNC}]
set_property PACKAGE_PIN AK29 [get_ports {PVO_VSYNC}]
set_property PACKAGE_PIN AE26 [get_ports {SII9616_INT}]

set_property IOSTANDARD LVCMOS33 [get_ports {PVO[35]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[34]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[33]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[32]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO_CLK}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO_DE}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO_HSYNC}]
set_property IOSTANDARD LVCMOS33 [get_ports {PVO_VSYNC}]
set_property IOSTANDARD LVCMOS33 [get_ports {SII9616_INT}]

set_property PACKAGE_PIN D17 [get_ports CLK_50M_0]
set_property PACKAGE_PIN F20 [get_ports CLK_50M_1]
set_property PACKAGE_PIN R28 [get_ports CLK_50M_2]
set_property PACKAGE_PIN R24 [get_ports CLK_50M_3]
set_property IOSTANDARD LVCMOS25 [get_ports {CLK_50M_0}]
set_property IOSTANDARD LVCMOS25 [get_ports {CLK_50M_1}]
set_property IOSTANDARD LVCMOS25 [get_ports {CLK_50M_2}]
set_property IOSTANDARD LVCMOS25 [get_ports {CLK_50M_3}]

# set_property PACKAGE_PIN A21 [get_ports {DMD_DDB_N[15]}]
# set_property PACKAGE_PIN K20 [get_ports {DMD_DDB_N[14]}]
# set_property PACKAGE_PIN H19 [get_ports {DMD_DDB_N[13]}]
# set_property PACKAGE_PIN F22 [get_ports {DMD_DDB_N[12]}]
# set_property PACKAGE_PIN C21 [get_ports {DMD_DDB_N[11]}]
# set_property PACKAGE_PIN C22 [get_ports {DMD_DDB_N[10]}]
# set_property PACKAGE_PIN E21 [get_ports {DMD_DDB_N[9]}]
# set_property PACKAGE_PIN H22 [get_ports {DMD_DDB_N[8]}]
# set_property PACKAGE_PIN B20 [get_ports {DMD_DDB_N[7]}]
# set_property PACKAGE_PIN A22 [get_ports {DMD_DDB_N[6]}]
# set_property PACKAGE_PIN L18 [get_ports {DMD_DDB_N[5]}]
# set_property PACKAGE_PIN B19 [get_ports {DMD_DDB_N[4]}]
# set_property PACKAGE_PIN F18 [get_ports {DMD_DDB_N[3]}]
# set_property PACKAGE_PIN A18  [get_ports {DMD_DDB_N[2]}]
# set_property PACKAGE_PIN J18  [get_ports {DMD_DDB_N[1]}]
# set_property PACKAGE_PIN H17  [get_ports {DMD_DDB_N[0]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[15]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[14]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[13]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[12]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[11]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[10]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[9]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[8]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[7]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[6]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[5]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[4]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[3]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[2]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_N[0]}]# 

# set_property PACKAGE_PIN A20 [get_ports {DMD_DDB_P[15]}]
# set_property PACKAGE_PIN K19 [get_ports {DMD_DDB_P[14]}]
# set_property PACKAGE_PIN J19 [get_ports {DMD_DDB_P[13]}]
# set_property PACKAGE_PIN G22 [get_ports {DMD_DDB_P[12]}]
# set_property PACKAGE_PIN D21 [get_ports {DMD_DDB_P[11]}]
# set_property PACKAGE_PIN D22 [get_ports {DMD_DDB_P[10]}]
# set_property PACKAGE_PIN F21 [get_ports {DMD_DDB_P[9]}]
# set_property PACKAGE_PIN H21 [get_ports {DMD_DDB_P[8]}]
# set_property PACKAGE_PIN C20 [get_ports {DMD_DDB_P[7]}]
# set_property PACKAGE_PIN B22 [get_ports {DMD_DDB_P[6]}]
# set_property PACKAGE_PIN L17 [get_ports {DMD_DDB_P[5]}]
# set_property PACKAGE_PIN C19 [get_ports {DMD_DDB_P[4]}]
# set_property PACKAGE_PIN G18 [get_ports {DMD_DDB_P[3]}]
# set_property PACKAGE_PIN B18  [get_ports {DMD_DDB_P[2]}]
# set_property PACKAGE_PIN K18  [get_ports {DMD_DDB_P[1]}]
# set_property PACKAGE_PIN J17  [get_ports {DMD_DDB_P[0]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[15]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[14]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[13]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[12]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[11]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[10]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[9]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[8]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[7]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[6]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[5]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[4]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[3]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[2]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDB_P[0]}]# 

# set_property PACKAGE_PIN G20  [get_ports {DMD_DCLKB_N}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DCLKB_N}]
# set_property PACKAGE_PIN H20  [get_ports {DMD_DCLKB_P}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DCLKB_P}]# 

# set_property PACKAGE_PIN D19  [get_ports {DMD_SCTRB_N}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_SCTRB_N}]
# set_property PACKAGE_PIN E19  [get_ports {DMD_SCTRB_P}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_SCTRB_P}]# 
# 

# set_property PACKAGE_PIN A28 [get_ports {DMD_DDA_N[15]}]
# set_property PACKAGE_PIN B25 [get_ports {DMD_DDA_N[14]}]
# set_property PACKAGE_PIN B29 [get_ports {DMD_DDA_N[13]}]
# set_property PACKAGE_PIN C26 [get_ports {DMD_DDA_N[12]}]
# set_property PACKAGE_PIN C30 [get_ports {DMD_DDA_N[11]}]
# set_property PACKAGE_PIN C27 [get_ports {DMD_DDA_N[10]}]
# set_property PACKAGE_PIN E26 [get_ports {DMD_DDA_N[9]}]
# set_property PACKAGE_PIN D28 [get_ports {DMD_DDA_N[8]}]
# set_property PACKAGE_PIN D24 [get_ports {DMD_DDA_N[7]}]
# set_property PACKAGE_PIN H25 [get_ports {DMD_DDA_N[6]}]
# set_property PACKAGE_PIN D23 [get_ports {DMD_DDA_N[5]}]
# set_property PACKAGE_PIN F27 [get_ports {DMD_DDA_N[4]}]
# set_property PACKAGE_PIN A26 [get_ports {DMD_DDA_N[3]}]
# set_property PACKAGE_PIN E30  [get_ports {DMD_DDA_N[2]}]
# set_property PACKAGE_PIN A27  [get_ports {DMD_DDA_N[1]}]
# set_property PACKAGE_PIN A23  [get_ports {DMD_DDA_N[0]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[15]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[14]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[13]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[12]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[11]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[10]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[9]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[8]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[7]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[6]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[5]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[4]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[3]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[2]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_N[0]}]# 

# set_property PACKAGE_PIN B28 [get_ports {DMD_DDA_P[15]}]
# set_property PACKAGE_PIN C25 [get_ports {DMD_DDA_P[14]}]
# set_property PACKAGE_PIN C29 [get_ports {DMD_DDA_P[13]}]
# set_property PACKAGE_PIN D26 [get_ports {DMD_DDA_P[12]}]
# set_property PACKAGE_PIN D29 [get_ports {DMD_DDA_P[11]}]
# set_property PACKAGE_PIN D27 [get_ports {DMD_DDA_P[10]}]
# set_property PACKAGE_PIN F26 [get_ports {DMD_DDA_P[9]}]
# set_property PACKAGE_PIN E28 [get_ports {DMD_DDA_P[8]}]
# set_property PACKAGE_PIN E24 [get_ports {DMD_DDA_P[7]}]
# set_property PACKAGE_PIN H24 [get_ports {DMD_DDA_P[6]}]
# set_property PACKAGE_PIN E23 [get_ports {DMD_DDA_P[5]}]
# set_property PACKAGE_PIN G27 [get_ports {DMD_DDA_P[4]}]
# set_property PACKAGE_PIN A25 [get_ports {DMD_DDA_P[3]}]
# set_property PACKAGE_PIN E29  [get_ports {DMD_DDA_P[2]}]
# set_property PACKAGE_PIN B27  [get_ports {DMD_DDA_P[1]}]
# set_property PACKAGE_PIN B23  [get_ports {DMD_DDA_P[0]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[15]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[14]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[13]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[12]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[11]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[10]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[9]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[8]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[7]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[6]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[5]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[4]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[3]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[2]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DDA_P[0]}]# 

# set_property PACKAGE_PIN F30  [get_ports {DMD_DCLKA_N}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DCLKA_N}]
# set_property PACKAGE_PIN G29  [get_ports {DMD_DCLKA_P}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_DCLKA_P}]# 

# set_property PACKAGE_PIN B24  [get_ports {DMD_SCTRA_N}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_SCTRA_N}]
# set_property PACKAGE_PIN C24  [get_ports {DMD_SCTRA_P}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_SCTRA_P}]# 

# set_property PACKAGE_PIN P22 [get_ports {DMD_BKP_N[41]}]
# set_property PACKAGE_PIN N24 [get_ports {DMD_BKP_N[40]}]
# set_property PACKAGE_PIN N22 [get_ports {DMD_BKP_N[39]}]
# set_property PACKAGE_PIN N30 [get_ports {DMD_BKP_N[38]}]
# set_property PACKAGE_PIN L20 [get_ports {DMD_BKP_N[37]}]
# set_property PACKAGE_PIN M23 [get_ports {DMD_BKP_N[36]}]
# set_property PACKAGE_PIN U25 [get_ports {DMD_BKP_N[35]}]
# set_property PACKAGE_PIN T21 [get_ports {DMD_BKP_N[34]}]
# set_property PACKAGE_PIN T27 [get_ports {DMD_BKP_N[33]}]
# set_property PACKAGE_PIN R26 [get_ports {DMD_BKP_N[32]}]
# set_property PACKAGE_PIN P28 [get_ports {DMD_BKP_N[31]}]
# set_property PACKAGE_PIN N20 [get_ports {DMD_BKP_N[30]}]
# set_property PACKAGE_PIN W22 [get_ports {DMD_BKP_N[29]}]
# set_property PACKAGE_PIN V22  [get_ports {DMD_BKP_N[28]}]
# set_property PACKAGE_PIN K21  [get_ports {DMD_BKP_N[27]}]
# set_property PACKAGE_PIN L23  [get_ports {DMD_BKP_N[26]}]
# set_property PACKAGE_PIN K24 [get_ports {DMD_BKP_N[25]}]
# set_property PACKAGE_PIN K25 [get_ports {DMD_BKP_N[24]}]
# set_property PACKAGE_PIN U28 [get_ports {DMD_BKP_N[23]}]
# set_property PACKAGE_PIN V30 [get_ports {DMD_BKP_N[22]}]
# set_property PACKAGE_PIN T23 [get_ports {DMD_BKP_N[21]}]
# set_property PACKAGE_PIN U30 [get_ports {DMD_BKP_N[20]}]
# set_property PACKAGE_PIN T30 [get_ports {DMD_BKP_N[19]}]
# set_property PACKAGE_PIN R29 [get_ports {DMD_BKP_N[18]}]
# set_property PACKAGE_PIN M27 [get_ports {DMD_BKP_N[17]}]
# set_property PACKAGE_PIN N26 [get_ports {DMD_BKP_N[16]}]
# set_property PACKAGE_PIN M30 [get_ports {DMD_BKP_N[15]}]
# set_property PACKAGE_PIN M25 [get_ports {DMD_BKP_N[14]}]
# set_property PACKAGE_PIN L27 [get_ports {DMD_BKP_N[13]}]
# set_property PACKAGE_PIN L28 [get_ports {DMD_BKP_N[12]}]
# set_property PACKAGE_PIN K29 [get_ports {DMD_BKP_N[11]}]
# set_property PACKAGE_PIN K30 [get_ports {DMD_BKP_N[10]}]
# set_property PACKAGE_PIN J28 [get_ports {DMD_BKP_N[9]}]
# set_property PACKAGE_PIN J26 [get_ports {DMD_BKP_N[8]}]
# set_property PACKAGE_PIN H27 [get_ports {DMD_BKP_N[7]}]
# set_property PACKAGE_PIN W24 [get_ports {DMD_BKP_N[6]}]
# set_property PACKAGE_PIN W26 [get_ports {DMD_BKP_N[5]}]
# set_property PACKAGE_PIN V24 [get_ports {DMD_BKP_N[4]}]
# set_property PACKAGE_PIN V27 [get_ports {DMD_BKP_N[3]}]
# set_property PACKAGE_PIN G24  [get_ports {DMD_BKP_N[2]}]
# set_property PACKAGE_PIN V20  [get_ports {DMD_BKP_N[1]}]
# set_property PACKAGE_PIN U23  [get_ports {DMD_BKP_N[0]}]

# set_property PACKAGE_PIN P21 [get_ports {DMD_BKP_P[41]}]
# set_property PACKAGE_PIN P23 [get_ports {DMD_BKP_P[40]}]
# set_property PACKAGE_PIN N21 [get_ports {DMD_BKP_P[39]}]
# set_property PACKAGE_PIN N29 [get_ports {DMD_BKP_P[38]}]
# set_property PACKAGE_PIN M20 [get_ports {DMD_BKP_P[37]}]
# set_property PACKAGE_PIN M22 [get_ports {DMD_BKP_P[36]}]
# set_property PACKAGE_PIN T25 [get_ports {DMD_BKP_P[35]}]
# set_property PACKAGE_PIN T20 [get_ports {DMD_BKP_P[34]}]
# set_property PACKAGE_PIN T26 [get_ports {DMD_BKP_P[33]}]
# set_property PACKAGE_PIN P26 [get_ports {DMD_BKP_P[32]}]
# set_property PACKAGE_PIN P27 [get_ports {DMD_BKP_P[31]}]
# set_property PACKAGE_PIN N19 [get_ports {DMD_BKP_P[30]}]
# set_property PACKAGE_PIN W21 [get_ports {DMD_BKP_P[29]}]
# set_property PACKAGE_PIN V21  [get_ports {DMD_BKP_P[28]}]
# set_property PACKAGE_PIN L21  [get_ports {DMD_BKP_P[27]}]
# set_property PACKAGE_PIN L22  [get_ports {DMD_BKP_P[26]}]
# set_property PACKAGE_PIN K23 [get_ports {DMD_BKP_P[25]}]
# set_property PACKAGE_PIN L25 [get_ports {DMD_BKP_P[24]}]
# set_property PACKAGE_PIN U27 [get_ports {DMD_BKP_P[23]}]
# set_property PACKAGE_PIN V29 [get_ports {DMD_BKP_P[22]}]
# set_property PACKAGE_PIN T22 [get_ports {DMD_BKP_P[21]}]
# set_property PACKAGE_PIN U29 [get_ports {DMD_BKP_P[20]}]
# set_property PACKAGE_PIN R30 [get_ports {DMD_BKP_P[19]}]
# set_property PACKAGE_PIN P29 [get_ports {DMD_BKP_P[18]}]
# set_property PACKAGE_PIN N27 [get_ports {DMD_BKP_P[17]}]
# set_property PACKAGE_PIN N25 [get_ports {DMD_BKP_P[16]}]
# set_property PACKAGE_PIN M29 [get_ports {DMD_BKP_P[15]}]
# set_property PACKAGE_PIN M24 [get_ports {DMD_BKP_P[14]}]
# set_property PACKAGE_PIN L26 [get_ports {DMD_BKP_P[13]}]
# set_property PACKAGE_PIN M28 [get_ports {DMD_BKP_P[12]}]
# set_property PACKAGE_PIN K28 [get_ports {DMD_BKP_P[11]}]
# set_property PACKAGE_PIN L30 [get_ports {DMD_BKP_P[10]}]
# set_property PACKAGE_PIN J27 [get_ports {DMD_BKP_P[9]}]
# set_property PACKAGE_PIN K26 [get_ports {DMD_BKP_P[8]}]
# set_property PACKAGE_PIN H26 [get_ports {DMD_BKP_P[7]}]
# set_property PACKAGE_PIN W23 [get_ports {DMD_BKP_P[6]}]
# set_property PACKAGE_PIN V25 [get_ports {DMD_BKP_P[5]}]
# set_property PACKAGE_PIN U24 [get_ports {DMD_BKP_P[4]}]
# set_property PACKAGE_PIN V26 [get_ports {DMD_BKP_P[3]}]
# set_property PACKAGE_PIN G23  [get_ports {DMD_BKP_P[2]}]
# set_property PACKAGE_PIN V19  [get_ports {DMD_BKP_P[1]}]
# set_property PACKAGE_PIN U22  [get_ports {DMD_BKP_P[0]}]


# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[41]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[40]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[39]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[38]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[37]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[36]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[35]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[34]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[33]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[32]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[31]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[30]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[29]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[28]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[27]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[26]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[25]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[24]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[23]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[22]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[21]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[20]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[19]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[18]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[17]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[16]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[15]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[14]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[13]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[12]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[11]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[10]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[9]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[8]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[7]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[6]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[5]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[4]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[3]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[2]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_N[0]}]# 
# 

# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[41]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[40]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[39]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[38]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[37]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[36]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[35]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[34]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[33]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[32]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[31]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[30]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[29]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[28]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[27]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[26]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[25]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[24]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[23]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[22]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[21]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[20]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[19]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[18]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[17]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[16]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[15]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[14]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[13]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[12]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[11]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[10]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[9]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[8]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[7]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[6]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[5]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[4]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[3]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[2]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[1]}]
# set_property IOSTANDARD LVDS_25 [get_ports {DMD_BKP_P[0]}]




set_property PACKAGE_PIN H30  [get_ports {DMD_RESETN}]
set_property PACKAGE_PIN H29  [get_ports {DMD_SCPENZ}]
set_property PACKAGE_PIN J29  [get_ports {DMD_SCPCK}]
set_property PACKAGE_PIN J21  [get_ports {DMD_SCPDO}]
set_property PACKAGE_PIN J22  [get_ports {DMD_SCPDI}]
set_property PACKAGE_PIN G17  [get_ports {DAD_ADDR[3]}]
set_property PACKAGE_PIN F17  [get_ports {DAD_ADDR[2]}]
set_property PACKAGE_PIN C17  [get_ports {DAD_ADDR[1]}]
set_property PACKAGE_PIN B17  [get_ports {DAD_ADDR[0]}]
set_property PACKAGE_PIN F25  [get_ports {DAD_SEL[1]}]
set_property PACKAGE_PIN E25  [get_ports {DAD_SEL[0]}]
set_property PACKAGE_PIN G28  [get_ports {DAD_MODE[1]}]
set_property PACKAGE_PIN F28  [get_ports {DAD_MODE[0]}]
set_property PACKAGE_PIN J24  [get_ports {DAD_OEZ}]
set_property PACKAGE_PIN J23  [get_ports {DAD_RESETN}]
set_property PACKAGE_PIN G30  [get_ports {DAD_SCPENZ}]
set_property PACKAGE_PIN A30  [get_ports {DAD_STROBE}]

set_property IOSTANDARD LVCMOS25 [get_ports {DMD_RESETN}]
set_property IOSTANDARD LVCMOS25 [get_ports {DMD_SCPENZ}]
set_property IOSTANDARD LVCMOS25 [get_ports {DMD_SCPCK}]
set_property IOSTANDARD LVCMOS25 [get_ports {DMD_SCPDO}]
set_property IOSTANDARD LVCMOS25 [get_ports {DMD_SCPDI}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_ADDR[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_ADDR[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_ADDR[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_ADDR[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_SEL[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_SEL[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_MODE[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_MODE[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_OEZ}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_RESETN}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_SCPENZ}]
set_property IOSTANDARD LVCMOS25 [get_ports {DAD_STROBE}]


# PadFunction: IO_L12P_T1_MRCC_33 
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_p}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_p}]
set_property PACKAGE_PIN AD12 [get_ports {sys_clk_p}]

# PadFunction: IO_L12N_T1_MRCC_33 
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_n}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_n}]
set_property PACKAGE_PIN AD11 [get_ports {sys_clk_n}]